const presidents = [
  {
    firstName: "George",
    lastName: "Washington",
    age: 57,
    party: "Independent",
  },
  { firstName: "John", lastName: "Adams", age: 61, party: "Federalist" },
  {
    firstName: "Thomas",
    lastName: "Jefferson",
    age: 57,
    party: "Democratic-Republican",
  },
  {
    firstName: "James",
    lastName: "Madison",
    age: 57,
    party: "Democratic-Republican",
  },
  {
    firstName: "James",
    lastName: "Monroe",
    age: 58,
    party: "Democratic-Republican",
  },
  {
    firstName: "John",
    lastName: "Quincy Adams",
    age: 57,
    party: "Democratic-Republican",
  },
  { firstName: "Andrew", lastName: "Jackson", age: 61, party: "Democratic" },
  { firstName: "Martin", lastName: "Van Buren", age: 54, party: "Democratic" },
  { firstName: "William Henry", lastName: "Harrison", age: 68, party: "Whig" },
  { firstName: "John", lastName: "Tyler", age: 51, party: "Whig" },
  { firstName: "James K.", lastName: "Polk", age: 49, party: "Democratic" },
  { firstName: "Zachary", lastName: "Taylor", age: 64, party: "Whig" },
  { firstName: "Millard", lastName: "Fillmore", age: 50, party: "Whig" },
  { firstName: "Franklin", lastName: "Pierce", age: 48, party: "Democratic" },
  { firstName: "James", lastName: "Buchanan", age: 65, party: "Democratic" },
  { firstName: "Abraham", lastName: "Lincoln", age: 52, party: "Republican" },
  {
    firstName: "Andrew",
    lastName: "Johnson",
    age: 56,
    party: "National Union",
  },
  { firstName: "Ulysses S.", lastName: "Grant", age: 46, party: "Republican" },
  {
    firstName: "Rutherford B.",
    lastName: "Hayes",
    age: 54,
    party: "Republican",
  },
  { firstName: "James A.", lastName: "Garfield", age: 49, party: "Republican" },
  { firstName: "Chester A.", lastName: "Arthur", age: 51, party: "Republican" },
  { firstName: "Grover", lastName: "Cleveland", age: 47, party: "Democratic" },
  { firstName: "Benjamin", lastName: "Harrison", age: 55, party: "Republican" },
  { firstName: "William", lastName: "McKinley", age: 54, party: "Republican" },
  {
    firstName: "Theodore",
    lastName: "Roosevelt",
    age: 42,
    party: "Republican",
  },
  { firstName: "William H.", lastName: "Taft", age: 51, party: "Republican" },
  { firstName: "Woodrow", lastName: "Wilson", age: 56, party: "Democratic" },
  { firstName: "Warren G.", lastName: "Harding", age: 55, party: "Republican" },
  { firstName: "Calvin", lastName: "Coolidge", age: 51, party: "Republican" },
  { firstName: "Herbert", lastName: "Hoover", age: 55, party: "Republican" },
  {
    firstName: "Franklin D.",
    lastName: "Roosevelt",
    age: 51,
    party: "Democratic",
  },
  { firstName: "Harry S.", lastName: "Truman", age: 60, party: "Democratic" },
  {
    firstName: "Dwight D.",
    lastName: "Eisenhower",
    age: 62,
    party: "Republican",
  },
  { firstName: "John F.", lastName: "Kennedy", age: 43, party: "Democratic" },
  { firstName: "Lyndon B.", lastName: "Johnson", age: 55, party: "Democratic" },
  { firstName: "Richard M.", lastName: "Nixon", age: 56, party: "Republican" },
  { firstName: "Gerald R.", lastName: "Ford", age: 61, party: "Republican" },
  { firstName: "Jimmy", lastName: "Carter", age: 52, party: "Democratic" },
  { firstName: "Ronald", lastName: "Reagan", age: 69, party: "Republican" },
  { firstName: "George H. W.", lastName: "Bush", age: 64, party: "Republican" },
  { firstName: "Bill", lastName: "Clinton", age: 46, party: "Democratic" },
  { firstName: "George W.", lastName: "Bush", age: 54, party: "Republican" },
  { firstName: "Barack", lastName: "Obama", age: 47, party: "Democratic" },
  { firstName: "Donald", lastName: "Trump", age: 73, party: "Republican" },
  { firstName: "Joe", lastName: "Biden", age: 78, party: "Democratic" },
];

export default presidents;
